[package]
name = "sffapi"
description = "Mish's unified Mini PC API"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
anyhow = "1.0.104"
argh = "0.1.19"
awc = { version = "3.8.2", default-features = false }
r2d2 = "0.8.10"
r2d2_sqlite = "0.35.0"
rusqlite = "0.40.2"
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json"] }
